[package]
edition = "2021"
name = "zome_1"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "zome_1"

[dependencies]
serde = "1"
derive_more = "0"

hdk = {version="0.0.124", features = ["encoding"]}
